# Generated by Django 3.1.6 on 2021-02-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=120)),
                ('asunto', models.CharField(max_length=300)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
