# Generated by Django 3.2.5 on 2021-07-30 19:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('publicacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.publicacion')),
                ('condicion', models.TextField(max_length=800, validators=[django.core.validators.MaxLengthValidator(800, '¡Máximo permitido 800 caracteres!')], verbose_name='condiciones')),
            ],
            options={
                'verbose_name': 'Adopcion',
                'verbose_name_plural': 'Adopciones',
            },
            bases=('apps.publicacion',),
        ),
    ]
