# Generated by Django 3.2.5 on 2021-07-30 19:00

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perdido',
            fields=[
                ('publicacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.publicacion')),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, '¡No se permiten edades negativas!'), django.core.validators.MaxValueValidator(25, '¡Máximo permitido 25 años!')])),
                ('fecha_perdido', models.DateField(help_text='¿Cuándo se perdió?', validators=[django.core.validators.MaxValueValidator(datetime.date(2021, 7, 30), '¡La fecha no puede ser mayor a hoy!')])),
                ('gratificacion', models.CharField(blank=True, help_text='Si ofrece gratificación detalle aqui', max_length=150, null=True)),
            ],
            bases=('apps.publicacion',),
        ),
    ]
