# Generated by Django 3.1.6 on 2021-02-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encontro',
            name='fecha_limite',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.CharField(default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='otro_dato',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perdido',
            name='gratificacion',
            field=models.CharField(default='S/G', max_length=5),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='entre_calles',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
