# Generated by Django 3.1.6 on 2021-02-24 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_evento',
            field=models.DateField(default=datetime.datetime(2021, 2, 24, 3, 22, 59, 532773)),
        ),
    ]
