# Generated by Django 3.1.6 on 2021-02-24 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdidos', '0002_auto_20210224_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_evento',
            field=models.DateField(default=datetime.datetime(2021, 2, 24, 13, 33, 28, 30740)),
        ),
    ]
