# Generated by Django 3.1.6 on 2021-02-24 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdidos', '0003_auto_20210224_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_evento',
            field=models.DateField(default=datetime.datetime(2021, 2, 24, 17, 0, 38, 883045)),
        ),
    ]
