# Generated by Django 3.2.5 on 2021-07-30 19:00

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Indica su nombre si lo conoces', max_length=30, null=True, validators=[django.core.validators.MaxLengthValidator(30, '¡Máximo permitido 30 caracteres!')])),
                ('especie', models.CharField(choices=[('Conejo', 'Conejo'), ('Gato', 'Gato'), ('Loro', 'Loro'), ('Perro', 'Perro'), ('Tortuga', 'Tortuga')], max_length=7, validators=[django.core.validators.MaxLengthValidator(7, '¡Máximo permitido 7 caracteres!')])),
                ('raza', models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.MaxLengthValidator(40, '¡Máximo permitido 40 caracteres!')])),
                ('tamano', models.CharField(choices=[('Grande', 'Grande'), ('Mediano', 'Mediano'), ('Chico', 'Chico')], max_length=7, validators=[django.core.validators.MaxLengthValidator(7, '¡Máximo permitido 7 caracteres!')])),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra'), ('Desconocido', 'Desconocido')], max_length=11, validators=[django.core.validators.MaxLengthValidator(11, '¡Máximo permitido 11 caracteres!')])),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='mascota')),
                ('otro_dato', models.TextField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255, '¡Máximo permitido 255 caracteres!')], verbose_name='Otra información')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(choices=[('Avia Terai', 'Avia Terai'), ('Campo Largo', 'Campo Largo'), ('Charata', 'Charata'), ('Colonia Benítez', 'Colonia Benítez'), ('Colonia Elisa', 'Colonia Elisa'), ('Colonias Unida', 'Colonias Unidas'), ('Comandancia Frías', 'Comandancia Frías'), ('Concepción del Bermejo', 'Concepción del Bermejo'), ('Coronel Du Graty', 'Coronel Du Graty'), ('Corzuela', 'Corzuela'), ('El Paranacito', 'El Paranacito'), ('El Sauzalito', 'El Sauzalito'), ('Fortín Belgrano', 'Fortín Belgrano'), ('Gancedo', 'Gancedo'), ('Gral. José de San Martín', 'Gral. José de San Martín'), ('Gral. Pinedo', 'Gral. Pinedo'), ('Hermoso Campo', 'Hermoso Campo'), ('Isla Soto', 'Isla Soto'), ('Juan José Castelli', 'Juan José Castelli'), ('La Clotilde', 'La Clotilde'), ('La Escondida', 'La Escondida'), ('La Leonesa', 'La Leonesa'), ('La Tigra', 'La Tigra'), ('La Verde', 'La Verde'), ('Las Breñas', 'Las Breñas'), ('Las Garcitas', 'Las Garcitas'), ('Las Hacheras', 'Las Hacheras'), ('Las Palmas', 'Las Palmas'), ('Los Frentones', 'Los Frentones'), ('Machagai', 'Machagai'), ('Makallé', 'Makallé'), ('Margarita Belén', 'Margarita Belén'), ('Miraflores', 'Miraflores'), ('Misión Nueva Pompeya', 'Misión Nueva Pompeya'), ('Napenay', 'Napenay'), ('Pampa del Indio', 'Pampa del Indio'), ('Pampa del Infierno', 'Pampa del Infierno'), ('Presidencia de la Plaza', 'Presidencia de la Plaza'), ('Presidencia Roca', 'Presidencia Roca'), ('Presidencia Roque Sáenz Peña', 'Presidencia Roque Sáenz Peña'), ('Puerto Bermejo', 'Puerto Bermejo'), ('Puerto Las Palmas', 'Puerto Las Palmas'), ('Puerto Tirol', 'Puerto Tirol'), ('Quitilipi', 'Quitilipi'), ('San Bernardo', 'San Bernardo'), ('Paraje San Fernando', 'Paraje San Fernando'), ('Santa Sylvina', 'Santa Sylvina'), ('Taco Pozo', 'Taco Pozo'), ('Tres Isletas', 'Tres Isletas'), ('Villa Ángela', 'Villa Ángela'), ('Villa Berthet', 'Villa Berthet'), ('Villa Río Bermejito', 'Villa Río Bermejito')], max_length=30, validators=[django.core.validators.MaxLengthValidator(30, '¡Máximo permitido 30 caracteres!')])),
                ('barrio', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, '¡Máximo permitido 50 caracteres!')])),
                ('calle', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(50, '¡Máximo permitido 50 caracteres!')])),
                ('numero', models.CharField(blank=True, default='S/N', max_length=5, null=True, validators=[django.core.validators.MaxLengthValidator(5, '¡Máximo permitido 5 caracteres!')])),
                ('entre_calles', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(50, '¡Máximo permitido 50 caracteres!')])),
                ('referencia', models.TextField(blank=True, max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(200, '¡Máximo permitido 200 caracteres!')], verbose_name='Alguna referencia')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('valido_hasta', models.DateField(default=datetime.date(2021, 8, 6), null=True)),
                ('fecha_entrega', models.DateField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2021, 7, 30), '¡La fecha no puede ser mayor a hoy!')])),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.mascota')),
                ('id_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apps.ubicacion')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
    ]
